url: http://www.cannedreporting.com
baseurl: /interlink2/

# Site settings
title: InterLink Marketing
email: jeff@interlinkmg.com
description: "InterLink Marketing Pleaston, California"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: F63909
  secondary: 171138  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Jeff Kyer
  pic: 2
  position: CEO
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Matt King
  pic: matt
  position: Director
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Nannette Andersen
  pic: nan
  position: Senior Director
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: #
  - title: facebook
    url:
  - title: stack-overflow
    url: #
  - title: bitbucket 
    url: #
  - title: github
    url: #

# Postal address (add as many lines as necessary)
address:
  - line: 5976 W Las Positas Blvd, Suite 126
  - line: Pleasanton, CA 94588

# Build settings
markdown: kramdown
permalink: pretty
