url: http://www.cannedreporting.com
baseurl: /interlink2/

# Site settings
title: InterLink Marketing
email: jeff@interlinkmg.com
description: "InterLink Marketing Pleaston, California"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: F63909
  secondary: f5f5f5f  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Jeff Kyer
  pic: jeff
  position: CEO
  social:
    - title: linkedin
      url: https://www.linkedin.com/pub/jeff-kyer/8/337/a03

- name: Matt King
  pic: matt
  position: Director
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/mattking1212

- name: Nannette Andersen
  pic: nan
  position: Senior Director
  social:
    - title: linkedin
      url: https://www.linkedin.com/pub/nannette-andersen/49/847/8b9


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
#  - title: linkedin
#    url: #


# Postal address (add as many lines as necessary)
address:
  - line: 5976 W Las Positas Blvd, Suite 126
  - line: Pleasanton, CA 94588

# Build settings
markdown: kramdown
permalink: pretty
